name = "indexnow-submitter"
main = "src/index.js"
compatibility_date = "2026-01-01"

routes = [
  { pattern = "www.claritywithai.org/3d29f2e57c0af6bfc57701004ab526d6.txt", zone_name = "claritywithai.org" },
  { pattern = "www.claritywithai.org/run-indexnow", zone_name = "claritywithai.org" }
]

[triggers]
crons = ["0 8 * * *"]

[[kv_namespaces]]
binding = "INDEXNOW_KV"
id = "14d53b11a38d4dcb83ecdbdc61294dd3"
